server.port: 8010

spring.autoconfigure.exclude:
  - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration


#freemarker

spring.freemarker.settings.object_wrapper: "beans"

#mongo config

mongodb:
  host: 127.0.0.1
  port: 27017